export const ProjectList = [
  {
    name: 'Hangman Game',
    image:
      'https://t4.ftcdn.net/jpg/05/17/38/33/360_F_517383341_8nWEFfM1KL3K5LNTjUDrne3x0kZiuxuj.jpg',
    skills: [
      'Typescript',
      'React.js',
      'HTML5',
      'CSS3',
      'Vite.js',
      'Styled-Components',
      'Javascript(ES6,EJS)',
    ],
    liveLink: 'https://hangman-game-play.vercel.app/',
    github: 'https://github.com/worm-codes/Hangman-TypeScript-Exercise',
    iframeLink: 'https://hangman-game-play.vercel.app/',
  },
  {
    name: 'ScreenShot to Drive',
    image: 'https://i.im.ge/2022/07/17/FlEt1J.png',
    skills: [
      'Node.js',
      'Bootstrap',
      'HTML5',
      'CSS3',
      'GoogleDrive API',
      'Javascript(ES6,EJS)',
    ],
    github: 'https://github.com/worm-codes/Screenshots_To_Drive',
    videoLink: 'https://www.youtube.com/embed/VvZHQJSGnBA',
  },
  {
    name: 'Local Guide',
    image: 'https://i.im.ge/2022/07/17/FlEflD.png',
    skills: [
      'Node.js',
      'React',
      'Socket.io',
      'Firebase(Auth)',
      'Bootstrap',
      'HTML5',
      'CSS3',
      'Javascript(ES6)',
    ],
    github: 'https://github.com/worm-codes/Local-Guide',
    videoLink: 'https://www.youtube.com/embed/4c8pnUydxaU',
  },
  {
    name: 'ERP Project',
    image:
      'https://i.ibb.co/RQbJPS4/sarah-ireland-morris-web-friendly-removebg-preview-1.png',
    skills: [
      'Node.js',
      'MongoDB',
      'Bootstrap',
      'HTML5',
      'CSS3',
      'Javascript(ES6,EJS)',
    ],
    github: 'https://github.com/worm-codes/ERP_Web_based_project',
    videoLink: 'https://www.youtube.com/embed/l6-2yVxLk7w',
  },
  {
    name: "Oguzhan's World",
    image: 'https://i.ibb.co/TTc8s61/vd.png',
    skills: [
      'Node.js',
      'MongoDB',
      'Semantic UI',
      'Bootstrap',
      'HTML5',
      'CSS3',
      'Javascript(ES6,EJS)',
    ],
    github: 'https://github.com/worm-codes/oguzhansworld',
    videoLink: 'https://www.youtube.com/embed/XRkdOgoiS8s',
  },
  {
    name: 'Color Game',
    image:
      'https://www.designer-daily.com/wp-content/uploads/2018/08/color-wheel.jpg',
    github: 'https://github.com/worm-codes/ColorGame_ReactNative',
    videoLink: 'https://www.youtube.com/embed/sCrzbP9WaJE',
    skills: ['React Native, Javascript'],
  },
];
